name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  buildExe:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # --- Yeni adımlar: macos-14 runner için Python + distutils desteği ---
      - name: Set up Python (macOS için distutils)
        if: runner.os == 'macOS'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python build deps (macOS)
        if: runner.os == 'macOS'
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            npm run build:linux
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run build:winexe
          else
            npm run build:mac
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # buildStore:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
      
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '20'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build Electron App
  #       run: npm run build:winstore
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload Microsoft Release
  #       uses: windows-store-publish@v1
  #       with:
  #         package-path: 'dist/*.appx'
  #         appId: ${{ secrets.WINDOWS_STORE_APP_ID }}
  #         publisherId: ${{ secrets.WINDOWS_STORE_PUBLISHER_ID }}
  #         skipSigning: true 
